### ISSUE TITLE
Consider update _schema.pyx to use cpdef

### ISSUE THREAD

**Issue by rhaarm** [fastavro/fastavro#196]
I noticed while doing Validators #182 that almost all of the Cython .pyx files use `cpdef` for function declarations, except `_schema.pyx`.

Based on this doc: http://notes-on-cython.readthedocs.io/en/latest/fibo_speed.html
I would assume that using cpdef in all cases would be the best thing to do, since it seems to provide a higher performance than just straight `def`.

Was this already attempted and why did it get revoked? Is it possible that these functions weren't usable outside of the cython declarations if declared with `cpdef`?

@scottbelden

**Comment by scottbelden** [comment]
I noticed that the article mentions `cpdef gives a good improvement over def because the recursive case exploits C functions`. I'm not sure if we would see the same performance in our case, but if the answer is that `cpdef` is always faster than `def` then I'm all for changing them.

The official [cython docs](http://cython.readthedocs.io/en/latest/src/userguide/language_basics.html#python-functions-vs-c-functions) aren't really clear to me on what's the fastest, but it seems like the answer might be `cdef` > `cpdef` > `def`. So in the `pyx` files, perhaps we should adhere to the following:

1. Use `cdef` for internal functions that aren't part of the public API
2. Use `cpdef` for functions that are part of the public API
3. Don't use `def`

Thoughts?

**Comment by rhaarm** [comment]
I think the use of `def` should be reserved for when the need to support of non cython import, but since this project has split them into multiple files we should default to `cpdef`.

**Comment by scottbelden** [comment]
Agreed.
