### ISSUE TITLE
Support Fingerprint

### ISSUE THREAD

**Issue by rhaarm** [fastavro/fastavro#201]
This is a feature to add, when doing a schemaless writer/reader, add support for avro schema fingerprints.

https://avro.apache.org/docs/1.8.2/spec.html#schema_fingerprints

Required to allow for: https://avro.apache.org/docs/1.8.2/spec.html#single_object_encoding

This is secondary benefit/feature:
Maybe this is how we handle #185 ? Change the SCHEMA_DEFS to store schemas via fingerprint or some dual purpose of fingerprint & namespace?

**Comment by scottbelden** [comment]
I think we should probably update the two schemaless functions to use the fingerprint by default so that it follows the spec. They were added before there was a spec for it which is why they don't currently do that.

And yes, it probably would help with storing multiple versions of a schema. However, I think it might require augmenting the original schema as well with the hash which we'd have to be careful about (we probably don't want to mutate the user's `schema` object that they pass in.

**Comment by rhaarm** [comment]
Ya sounds good to me. Do we know if the apache/avro package does the BOM? Also, I'm going to refer to it as a BOM, since that's kinda what it is... :-/

**Comment by Plonk42** [comment]
Hi,
Any news/plan on this thread? We are using fastavro and would like to use single-object encoding with schema fingerprinting. Thanks!

**Comment by scottbelden** [comment]
@Plonk42 No updates at the moment. PRs are welcome. Otherwise its something that I'll try to get to at some point.
