### ISSUE TITLE
Identifying the type of a record in a union of records

### ISSUE THREAD

**Issue by chobeat** [fastavro/fastavro#205]
Hello,

let's say I have a union of records at the root level. We can call these two types: "Left" and "Right". Let's say I want to know if a message I receive is Left or Right without checking against the field they contains (because maybe they can be the same, not my case, but in theory it can happen). Is it possible to do so with fastavro? Does the serialized message contain information regarding the actual type of the specific message? Does it make sense to request a feature where we retrieve the "Name" field of the type of a given message?

**Comment by scottbelden** [comment]
For a normal avro record that includes the header this would be quite difficult. First, you'd have to read past the header (which isn't too hard), but then you'd have to look at the header to know if the data was compressed and decompress it, and then maybe one other operation before you even get to the encoded record. At that point, I'm not sure you'd be much better off than just parsing the entire binary.

If you have binary that was written with the `schemaless_writer`, then this becomes easier. In your case you would just need to read the first `long` that is encoded (since in the case of unions, they are encoded first by writing out the zero based index of the schema). So for example, this script prints out the index of the schema that was written and the name of the schema:

```python
from io import BytesIO

from fastavro.read import read_data
from fastavro.write import schemaless_writer, writer

from fastavro._read_py import read_long

schema = [
    {
        "type": "record",
        "name": "Left",
        "fields": [{
            "name": "b",
            "type": "string"
        }]
    },
    {
        "type": "record",
        "name": "Right",
        "fields": [{
            "name": "c",
            "type": "string"
        }]
    }
]

binary1 = BytesIO()
schemaless_writer(binary1, schema, {'b': 'foo'})
binary1.seek(0)

binary2 = BytesIO()
schemaless_writer(binary2, schema, {'c': 'foo'})
binary2.seek(0)

index1 = read_long(binary1)
index2 = read_long(binary2)

print('binary1 index is {0} which is record {1}'.format(index1, schema[index1]['name']))
# binary1 index is 0 which is record Left
print('binary2 index is {0} which is record {1}'.format(index2, schema[index2]['name']))
# binary2 index is 1 which is record Right
```

However, you'll note that `read_long` isn't a part of the public API (and I'm not sure that it makes sense to have it part of the public API). Also, this feels like a very specific use case and I'm not sure how generalizable it is so I don't know if it would be good to add it. For example, by script wouldn't work if the top level union included a primitive string as an option (as it doesn't have a `name`)

**Comment by chobeat** [comment]
it is indeed specific. Nonetheless it looks like a necessary feature to really handle unions of records in a dynamically typed language. I will most likely change my approach and encode the type as an enum "message_type" field and the rest as an "outcome" field and read this field according to the "message_type" using different functions

**Comment by chobeat** [comment]
Yes, precisely.

**Comment by scottbelden** [comment]
I believe this was resolved in https://github.com/fastavro/fastavro/pull/370. There is a `return_record_name` that can be set to `True`. When `True`, a union will be decoded as a tuple of the record name and the record.
