### ISSUE TITLE
Non list Aliases Pass Schema Acquaint

### ISSUE THREAD

**Issue by rhaarm** [fastavro/fastavro#206]
We have some upload functionality that verifies a schema is valid with `fastavro.acquaint_schema`, then once it's passed it gets sent to Schema Registry, which is kicking it back as invalid avro with no indicator of where the error actually is. After deleting 1 field at a time to narrow down which is was, I discovered an "aliases" was set to just a string, when the Avro spec requires a list. Since `acquaint_schema` does validate "aliases", this will lead into a runtime error or unexpected behavior eventually, when a string get's chunked into multiple characters, vs treated as a single value in a list.

So in efforts like the Validators branch, let's design a feature that validates a schema and does not store it in SCHEMA_DEFS, WRITERS, READERS dictionaries. Has better log errors/exceptions with the Avro schema.

Should we look at using the apache/avro python schema for validation of a schema? It's probably just as bad for giving erroneous error messages as Schema Registry (running with Java Avro library).

**Comment by scottbelden** [comment]
There are quite a few good points here.

1. Having some ability to do real schema validation definitely seems like a good idea. Up until recently if you gave `fastavro` a schema of a record without a `name` field (required by the spec) we wouldn't complain but that was fixed in https://github.com/tebeka/fastavro/pull/187. However, `enum` and `fixed` types are also supposed to have a `name` field and we don't check that.

2. `acquaint_schema` probably shouldn't be a part of the API. It's not documented and it feels like something internal that an outsider shouldn't have to know about what it does. If we do this, we probably need to evaluate if it makes sense to have `read_data` be a part of the API as well [since there's at least some cases where calling `acquaint_schema` is necessary](https://github.com/tebeka/fastavro/issues/101#issuecomment-331520263).

3. I don't think the apache/avro python library would help much here. I'm not sure it even supports aliases so it probably doesn't even look at that part of the schema.

It seems like it wouldn't be too hard to have some `validate_schema` function. We'd just want to make sure that we aren't duplicating too much code between the validate function and what happens during `acquaint_schema` (at the moment that might only be that checking for a record `name`).
