### ISSUE TITLE
Appending to an existing avro file

### ISSUE THREAD

**Issue by ellimilial** [fastavro/fastavro#276]
Is it possible to append to an already existing `avro` file, possible with `writer` interface?

When opening a file in `ab` mode, upon reading I encounter `ValueError: expected sync marker not found`. `r+b` mode doesn't seem to do any appending.

**Comment by scottbelden** [comment]
At the moment it is not. I looked through the `apache/avro` code and at least the Java implementation has an [`appendTo` function](https://github.com/apache/avro/blob/673261c8656124cc58bee65fe5e8c779350779ee/lang/java/avro/src/main/java/org/apache/avro/file/DataFileWriter.java#L191-L229) that I believe does something like this.

I'll need to think about how this would work and if it's possible. The avro file format is separated into `blocks`, but I think we should be able to add a new block(s) with the new record(s).

**Comment by scottbelden** [comment]
@ellimilial I will probably merge https://github.com/fastavro/fastavro/pull/278 soon. The way it will work is that if you open a file in `wb` mode, it will write like normal. However, if you open it in `a+b` (append and readable) mode then it will append to the file. If you open it in just `ab` mode an error should be raised because we need to be able to read some of the header information from the original file in order to append correctly.

**Comment by ellimilial** [comment]
Thank you so much for looking into it @scottbelden (and the speed)!
