### ISSUE TITLE
Any guidance on implementing serialization from/deserialization to custom classes?

### ISSUE THREAD

**Issue by dmsolow** [fastavro/fastavro#287]
It's often perfectly fine to serialize dicts/lists/etc into avro, and deserialize avro into dicts/lists/etc. However sometimes it would be nice to use custom classes to hold the data while it's in Python.

This is possible in the standard python JSON module, for example, using the `object_hook` argument. Something similar should be possible in avro. For deserializing, a function could take `schema` and `object` as arguments where `object` is whatever dict/list/etc was parsed, and `schema` is the avro schema of that object. The function body could then make a decision on whether to return the default `object` or instantiate a new object to return. 

I'm curious how I might begin to implement something like this using the fastavro library. If anyone has any guidance, I'd really appreciate it.

**Comment by scottbelden** [comment]
I completely agree about the usefulness of classes over dictionaries. However, this will be no easy task (which is why I haven't attempted to do it yet). Here's a few things to consider:

1. This would be big breaking change

We'd probably want a way to configure `fastavro` to either return dictionaries or these classes. Currently we don't have any good way of configuring options like this. I do have an idea of how this could be done that I am toying with in a branch to resolve https://github.com/fastavro/fastavro/issues/205. I don't think this will be a big problem, but just something to remember.

2. We would need to define an interface for the classes

This is probably not too difficult, but there are some details that would have be kept in mind. For example, we might expect a record class to have an attribute called `schema` that would hold the schema of the record but if the class also has attributes for each field then a field named `schema` would cause a collision. Therefore, we'd probably need to have details like the `schema`, `name`, `namespace`, etc be prefixed with an underscore.

3. Performance needs to be maintained

This is what I'm most worried about. In particular, cython seems to be much more performant when working with dictionaries. Now, I'm sure there are ways to keep the performance when working with class objects but I have a feeling that it might require more direct usage of the Python C API.

Overall, I still think this would be a great addition. If you wanted to give this a shot, I think a good proof of concept would be a branch that is capable of returning some sort of `Record` class instead of dictionaries. The `Record` class to begin with could just be something that has attributes for each of the fields so that when you do `record.field1_name` it would return the value of that field. Once that is in place we could benchmark it against the current implementation to make sure the performance doesn't suffer. This initial branch wouldn't necessarily need to have the tests passing or be configurable (it could always return the class objects and ignore the fact that it's a breaking change).

**Comment by dmsolow** [comment]
So I think my perspective on this is a little different. I would say a lot of the power of something like I'm suggesting comes when you support custom user classes. And if you're supporting any user class, it's probably impossible to maintain performance.

I'm going to think about my use-case, and maybe try to monkey-patch something in, and we'll see what happens.

**Comment by scottbelden** [comment]
Okay. I'm interested to see what you come up with. Let me know if there's anything I can assist with.

**Comment by dmsolow** [comment]
I've started working on serialization, and I quickly ran into the problem that I think is described in #205 

I think you already understand this problem, but let me explain what I think is causing it, and you can confirm.

My schema has several records with fields like this:
```
{
    "name": "attributes",
    "default:": [],
    "type": {
        "type": "array",
        "items": [
            "test.attr.Name",
            "test.attr.FavoriteColor",
            "test.attr.Address"
        ]
    }
}
```
Each of the named types in the `items` union are previously defined records. 

I realize that there's a simple way to accomplish something like this using fields different (i.e. make a field for `Name`, `FavoriteColor` and `Address` respectively). However I'm doing it this way for a reason, and it is absolutely something that the avro spec supports. On unions the spec state: 

> Unions may not contain more than one schema with the same type, except for the named types record, fixed and enum. For example, unions containing two array types or two map types are not permitted, but two types with different names are permitted. (Names permit efficient resolution when reading and writing unions.)

Since my union only contains named types (records), it should be able to contain any number of named types.

Also I've validated my full schema using third party tools, the officlal python avro library, and fastavro, so I'm 100% sure my schema is valid.

My first try at serialization in this approach is to turn everything into dictionaries and lists and try to serialize. It seems like this is failing because fastavro cannot infer the record type of the the dictionary that represents one of the unioned records.

This is understandable -- without passing the record name to fastavro, it cannot possibly be expected to figure out which record type it is. This is what I think #205 is about.

Again I think you already understand this problem, but I just wanted to get my head wrapped around it before proceeding.

I'm thinking (as you state in #205) that the solution here is to add a custom key that identifies the record type. However I don't know that this is sufficient. What if I have a union of two enum types? How would you give a hint to fastavro that a string has a certain type?

My feeling is that the solution is to move away from this generic approach that uses dicts, strings, etc. If you lose performance that's a shame, but at least you would fully support the avro spec.

**Comment by dmsolow** [comment]
Okay I looked at the `write_union` function and realized that you have a solution for this in 0.21.9 -- gonna try with tuples

**Comment by scottbelden** [comment]
The tuple solution works for being able to specify the type when writing. However, https://github.com/fastavro/fastavro/issues/205 still has a legitimate reason for existing which is that when reading you will get back the object but not know what type it is. I have a branch where I started working on a solution to here: https://github.com/fastavro/fastavro/compare/issue205. That branch would allow someone to set an option that would tell the reader to return union values as tuples too. However, I haven't had time recently to finish it up.

**Comment by dmsolow** [comment]
I'm skeptical about tuples being a final solution for this, just because it pushes the decision-making onto the user. The user will have to define a protocol to decide what happens when a tuple vs. dict is returned.

I also don't think the user should be responsible for creating a tuple vs. dict because that requires knowledge of whether the record in question is part of a union.

So I'll think about whether I can come up with something better and see if I can contribute a branch.

**Comment by scottbelden** [comment]
Yeah, it's not the most clean solution. I think the best would be to have actual classes returned rather than dicts, but it would hopefully be a stopgap until the better solution was developed.

**Comment by dmsolow** [comment]
@scottbelden I forked the repo and made some changes. My changes are very much not ready for merging for multiple reasons (for one, I only edited `.py` files), I just want to move the discussion forward.

You can see what I did [here](https://github.com/dmsolow/fastavro/commit/6a4a094f9805b0f3ba3d9dc63f43b6323aa8b7a7)

To add custom user classes, I added an argument `custom_type_map` that can optionally be passed to a reader function. The argument maps from the fully-qualified (i..e namespaced) avro type name to a constructor class. For example:

```
class RecordA:
   # ...
   pass

custom_type_map = {
    "com.avro.test.RecordA": RecordA
}
```

If `custom_type_map` is passed to a reader function, instances of `com.avro.test.RecordA` returned by the reader will be members of the `RecordA` class instead of the `dict` class. To support this, the `RecordA` class needs a constructor that takes three arguments `name`, `schema`, and `data`. 

To support writing records like this, I changed the `write_union` function to look for an attribute called `name` instead of a tuple. The value of `name` is used to determine the type to write. `name` may be a bad choice for this, since it's too common a variable name (i.e. it's possible that a user would want to use `name` for their own purposes).

I also changed how generic records are read. After some thought I think it's a good choice to use `dicts` to express generic records (because this isn't Java after all), but I think it's important that the generic types allow the user to access the fully qualified name of the avro type.

To support this, I added classes in  `_read_py.py`: `GenericRecord` (subclasses `dict`) `GenericFixed` (subclasses `bytes`) and `GenericEnum` (subclasses `str`). The only different between these classes and their superclass is that they have a `name` member (the fully qualified avro type name) and a `schema` member (the avro schema).

I think this is important because I have uses-cases where I am reading generic records from an array with union type records. I want to be able to loop over the items in this array and take an action based on the type of the record. And I'd prefer to be able to do this with generic records, because I may not want to provide generated classes for every single reader. 

This is a use-case that avro supports, but I don't believe it's possible to support it without tagging all deserialized data with their proper names.

**Comment by scottbelden** [comment]
Is the custom class aspect a feature that you would actively use? I suspect most people would find the `GenericRecord` class sufficient.

I like how `GenericRecord` subclasses `dict` so that (I think...) there is no breakage. It does make the class feel a little weird to use because things like `name` and `schema` are attribute lookups (e.g. `record.name`) where as the fields are dictionary lookup (e.g. `record['field1']`), but that could be tweaked in the future if needed.

I'm not sure I understand why `GenericFixed` and `GenericEnum` have a `schema` attribute. That seems like it should only exist for records.

Overall, it seems like a good direction. The main barrier to merging it in would be performance costs. I know it's probably not something you've looked at yet but we would need to make sure that performance isn't degraded by using classes rather than the builtin types.

**Comment by dmsolow** [comment]
I would use both the custom classes and `GenericRecord`s in various circumstances. This kind of hinges on what I actually do for my work, but I think my use-cases are widely applicable

For transforming non-avro data to avro, I generally want to use custom classes. I have a library that takes an avro schema and generates python classes for each named type in the schema. This generated code can then be imported into the "avro-creator." This is nice, for example, because setting a nonexistent field in a record class becomes an error then and there, whereas with a  `dict` it's only an error when the `dict` is serialized to avro. These generated classes also make the code a lot more readable and they eliminate "magic strings" used for record field names and enums, which is highly desirable.

However once the data is in avro, follow-on processes that read and mutate the data don't necessarily need to use custom classes. It might be useful to use custom classes occasionally, but I also want to be able to write processors that can read and react to avro records with multiple schemas without necessarily providing generated code for every possible schema. `GenericRecords` are good for this, and there's less of an opportunity for mistakes that produce invalid records, because the input data is guaranteed to be valid avro.

As far as the `GenericFixed` and `GenericEnum`, the main case where you'd want the schema is for custom logicalTypes. I haven't tested my code to see if it supports this, but it's a major goal. If my schema has a logicalType that's not supported by `fastavro` I want to be able to detect that and deal with it properly after it's deserialized from avro. This might be done, for example, in a custom class. But I want it to be possible to do this with generic classes as well.

As I type this, I realize that this applies to non-named types as well, so technically there should be a `GenericInt`, `GenericString`, etc... I don't know about all of that. but it bears thinking about at least.

**Comment by scottbelden** [comment]
Is the library that you have that creates the avro classes open source? That sounds interesting and something I have contemplated doing in the past but never got around to it.

I agree that a `GenericInt` and `GenericString` feel like overkill but I can see what you mean. If you went down that path you'd basically have to create a `Generic...` for every type because you could have a custom logical type for basically any type.

**Comment by dmsolow** [comment]
It's not open source right now, but it likely could be. If I get permission I'd be happy to share it.

One concern is what `fastavro` wants to support vs. what my code wants to support. Right now I generate python classes that use the (dataclasses)[https://docs.python.org/3/library/dataclasses.html] module, which was added in python 3.7. I imagine that `fastavro` would need to support older versions. This would not be too difficult to add, but it's something to consider

**Comment by scottbelden** [comment]
Oh, yeah, I don't know that it would be incorporated into this project. I just thought it would be interesting to look at. Of course if there are reasons it can't be open sourced then it's not a big deal.

**Comment by redsk** [comment]
Hi @scottbelden , I've written an open source library to generate python classes from avro schemas. It's available at https://gitlab.com/Jaumo/pyavro-gen . It also includes some bits to integrate it with fastavro, Kafka and the Schema Registry (as this is required for my use case). 

I also used dataclasses (python 3.7) but I guess it would be possible to consider support for older versions as well.

Please let me know if you're interested.

**Comment by scottbelden** [comment]
@redsk Cool! I'm interested to take a look at it, so hopefully I can do that soon.

**Comment by ksunden** [comment]
```python
import fastavro  # type: ignore


class Interface:
    def __init__(self, array_interface):
        array_interface["shape"] = tuple(array_interface["shape"])
        self.__array_interface__ = array_interface


def read_ndarray(data, writer_schema, reader_schema):
    import numpy as np  # type: ignore

    return np.array(Interface(data))


def prepare_ndarray(data, schema):
    if hasattr(data, "__array_interface__"):
        array_interface = data.__array_interface__.copy()
        array_interface["data"] = data.tobytes()
        array_interface["shape"] = list(array_interface["shape"])
        return array_interface
    else:
        return data


fastavro.read.LOGICAL_READERS["record-ndarray"] = read_ndarray
fastavro.write.LOGICAL_WRITERS["record-ndarray"] = prepare_ndarray
```

It is possible to use `logicalType` to get this kind of behavior. e.g. this example which serailizes ndarrays using this schema:

```
{'fields': [{'name': 'shape', 'type': {'items': 'int', 'type': 'array'}},
            {'name': 'typestr', 'type': 'string'},
            {'name': 'data', 'type': 'bytes'},
            {'name': 'version', 'type': 'int'}],
 'logicalType': 'ndarray',
 'name': 'ndarray',
 'type': 'record'}
```

(See https://numpy.org/devdocs/reference/arrays.interface.html for more info on the fields)

**Comment by scottbelden** [comment]
@ksunden I'm not exactly sure what you are asking. Are you asking to add that code to the current set of logical readers/writers or are you giving an example of some code you have that currently works for you?

**Comment by ksunden** [comment]
I am giving an example of code that works

**Comment by scottbelden** [comment]
Here is another option for people looking for custom class generation: https://github.com/fastavro/fastavro/issues/506.

I'm going to close this as this is not something that I expect will be added to fastavro.
