### ISSUE TITLE
Validate fails for union fields default values

### ISSUE THREAD

**Issue by m0nhawk** [fastavro/fastavro#291]
I have the following code:

```
import json

from fastavro import writer, parse_schema, reader
from fastavro.validation import validate_many

if __name__ == '__main__':
    schema = open("schema/test.avsc", "rb").read()
    schema = json.loads(schema)
    parsed_schema = parse_schema(schema)

    records = [{'name': 'foo'}, {'name': 'bar', 'datetime': 'haha'}]

    with open('test.avro', 'wb') as out:
        writer(out, parsed_schema, records)

    with open('test.avro', 'rb') as fo:
        avro_reader = reader(fo)
        for record in avro_reader:
            print(record)

    validate_many(records, parsed_schema)
```

And the output:

```
{'name': 'foo', 'datetime': None}
{'name': 'bar', 'datetime': 'haha'}
Traceback (most recent call last):
  File "write.py", line 21, in <module>
    validate_many(records, parsed_schema)
  File "fastavro/_validation.pyx", line 214, in fastavro._validation.validate_many
  File "fastavro/_validation.pyx", line 225, in fastavro._validation.validate_many
fastavro._validate_common.ValidationError: [
  "test.datetime is <<object object at 0x1085e01f0>> of type <class 'object'> expected null",
  "test.datetime is <<object object at 0x1085e01f0>> of type <class 'object'> expected string"
]
```

It does work (script outputs both records correctly with `None` for missing union item), but the `validate_many` and `validate` doesn't work.

My schema:

```
{
  "type" : "record",
  "name" : "test",
  "fields" : [ {
    "name" : "name",
    "type" : "string"
  }, {
    "name" : "datetime",
    "type" : [ "null", "string" ]
  } ]
}
```

`avro-tools` works well also.

**Comment by scottbelden** [comment]
Thanks for the detailed report again!

In your example, it seems that the validation code is more strict than the normal avro writer code. However, instead of the validation being too strict, I think the problem is that the writer is not strict enough.

The writer does a check to see if the field name exists, or there is a default defined, or `null` is a valid type and if so it implicitly acts like the value for the field was set to `None`. However, this is wrong, and can be seen by running this example:

```python
import json

from fastavro import writer, parse_schema, reader
from fastavro.validation import validate_many, validate

schema = {
    "type": "record",
    "name": "A",
    "fields": [{"name": "foo", "type": ["string", "null"]}]
}

parsed_schema = parse_schema(schema)

records = [
    {'foo': 'foo'},
    {'foo': None},
    {'bar': 'huh?'},
]

with open('test.avro', 'wb') as out:
    writer(out, parsed_schema, records)

with open('test.avro', 'rb') as fo:
    avro_reader = reader(fo)
    for record in avro_reader:
        print(record)
```

The output from that is currently:

```
{'foo': 'foo'}
{'foo': None}
{'foo': None}
```

In the case of the `{'bar': 'huh?'}` record, the code doesn't find a `foo` field or a default value, but since the type is a union that contains `null` as a potential value it essentially treats the record as if it were `{'bar': 'huh?', 'foo': None}`.

I looked for other examples of this type of problem and came about this avro issue from a few years ago: https://issues.apache.org/jira/browse/AVRO-1803?focusedCommentId=15165682&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-15165682

I think that ticket is a similar issue and states that when you have a union, you should either have an explicit value or have a default value defined. The current behavior of `fastavro` to implicitly set the value to `None` in some cases is wrong.

Therefore, if there's a chance you wouldn't be setting the `datetime` field to a value, I think your schema should be the following:

```
schema = {
  "type" : "record",
  "name" : "test",
  "fields" : [ {
    "name" : "name",
    "type" : "string"
  }, {
    "name" : "datetime",
    "default": None,
    "type" : [ "null", "string" ]
  } ]
}
```

**Comment by m0nhawk** [comment]
Thank you for the explanation, now I understand that this is a tolerance of writer, not validator. And not a bug.

The fix with default value works for me perfectly.

**Comment by scottbelden** [comment]
I made a new issue https://github.com/fastavro/fastavro/issues/292 to remind me that the writer should be more strict. I don't know when it will get done and it is potentially a big breaking change so I'll have to keep that in mind before pushing it into a release.
