### ISSUE TITLE
reader_schema ignored when dealing with doubles

### ISSUE THREAD

**Issue by afiodorov** [fastavro/fastavro#302]
The following code:

```
import fastavro
import io

records = [{'a': 1000}, {'a': 14}]

write_schema = {
    "name": "test",
    "type": "record",
    "fields": [
        {"name": "a", "type": "long"}
    ]
}

read_schema = {
        "name": "test",
        "type": "record",
        "fields": [
            {"name": "a", "type": "double"}
        ]
    }

out = io.BytesIO()
fastavro.writer(out, fastavro.parse_schema(write_schema), records)
data = out.getvalue()

reader = fastavro.reader(io.BytesIO(data), reader_schema=fastavro.parse_schema(read_schema))
print(list(reader))
```

Produces the output
> [{'a': 1000}, {'a': 14}]

However, as the `read_schema` says type of `a` is `double`, I anticipate the following output:
> [{'a': 1000.0}, {'a': 14.0}]

Is this a bug or is this expected?

**Comment by scottbelden** [comment]
I double checked and I believe the reader schema is being validated as matching (since an `long` is promotable to a `double`). If you instead had `string` instead of `double`, we would get the expected error: `SchemaResolutionError: Schema mismatch: long is not string`.

However, you are correct that it doesn't look like we are then taking the reader schema and using it (we are simply checking that it conforms to the schema evolution rules). I need to look at the java implementation and see what they do to know what is "right". I'll try to take a look soon, but it might be a week or two as the holidays are closing in.

One side note is that python doesn't have a `double` type, so it's questionable if the output should be a float of `14.0` or what it should be. It's worth noting that if you remove the `write_schema` from your example and just have:

```python
import fastavro
import io

records = [{'a': 1000}, {'a': 14}]

read_schema = {
        "name": "test",
        "type": "record",
        "fields": [
            {"name": "a", "type": "double"}
        ]
    }

out = io.BytesIO()
fastavro.writer(out, fastavro.parse_schema(read_schema), records)
data = out.getvalue()

reader = fastavro.reader(io.BytesIO(data), reader_schema=fastavro.parse_schema(read_schema))
new_records = list(reader)
print(new_records)
```

Then it treats the `14` as a `double` and is able to write and read just fine with the output being `[{'a': 1000.0}, {'a': 14.0}]`.

Is this currently causing an error for you somewhere or is it just something that looked a little funny?

**Comment by afiodorov** [comment]
Thanks for the reply.

>Is this currently causing an error for you somewhere or is it just something that looked a little funny?
At Nstack it currently causes us an error because we deal with CSV files and infer types for fields when we encode, but occasionally, we do know the types for certain fields when we decode. However the decoding appears to only validate but not convert in this case - forcing us to consider adding an additional cast after the decoding step.
