### ISSUE TITLE
ValueError when saving datetime64[ns] value that contains the NaT value

### ISSUE THREAD

**Issue by simonejsing** [fastavro/fastavro#313]
I'm getting a ValueError when trying to save a pandas data frame using 'pandavro' which wraps 'fastavro'. This error happens when a datetime64[ns] column contains a None/NaT value.

The following snippet reproduces the error:
```
import pandavro as pdx
import pandas as pd
import datetime as dt

df = pd.DataFrame({ 'col': [dt.datetime.utcnow(), None] })
print(df[df['col'].isna() == True])
print(df['col'].dtypes)
pdx.to_avro('temp.avro', df)
```

And raises the error:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
pandas/_libs/tslibs/nattype.pyx in pandas._libs.tslibs.nattype._make_error_func.f()

ValueError: NaTType does not support timestamp

Exception ignored in: 'fastavro._write.prepare_timestamp_micros'
Traceback (most recent call last):
  File "pandas/_libs/tslibs/nattype.pyx", line 59, in pandas._libs.tslibs.nattype._make_error_func.f
ValueError: NaTType does not support timestamp

Is this behavior expected? Can I not save NaT values for datetime values in AVRO files?

Thanks

**Comment by scottbelden** [comment]
I had never heard of a `NaT` and had to look it up to see what it is. To answer the immediate question, there is currently no support for a `NaT` type.

To dig into this some, when serializing a time in avro, they are usually represented as an `int` or a long` (such as number of days after the epoch, number of seconds past midnight, etc). I'm not sure what value would make sense for a `NaT`. The avro specification doesn't appear to have any information regarding how to serialize something like "not a time".

Therefore, I think the correct option would be to have either `pandavro` or your own code do something where it change a `NaT` to some valid value that can be serialized and then when reading if it finds that known value it changes it back to a `NaT`.

Let me know if I'm misunderstanding something or if you have any other thoughts. Thanks!

**Comment by rhaarm** [comment]
Agreed, I have bit more experience with Pandas and this is not a direct
issue with Avro or Fastavro. You will need to place this issue on pandavro
to handle NaT types, possibly convert them to python None.

**Comment by simonejsing** [comment]
Thanks for the fast feedback on this issue. Does the avro format support Null/None values? If that's the case I would look for a solution that uses Null to represent NaT.

**Comment by scottbelden** [comment]
Yes, it does support a `null` type (represent in python as `None`). I've never used `pandavro`, but it looks like it sees that you have some datetime-like object and [says that the avro logical type `timestamp-micros` should be used (which is probably fine)](https://github.com/ynqa/pandavro/blob/f0431a0aa970851e90b12ab9f51c989105013084/pandavro/__init__.py#L22). It does go on to say that the [real avro schema is a union of null and that logical type](https://github.com/ynqa/pandavro/blob/f0431a0aa970851e90b12ab9f51c989105013084/pandavro/__init__.py#L31). So I think somewhere in there it should say "Oh, I have a `NaT`, so I should change this to `None` when avro serializing`.

This transformation of a `NaT` to a `None` value for serializing shouldn't be done in `fastavro` because the concept of a `NaT` is not defined for avro. When reading the avro file where a field is either `null` or a `timestamp-micros`, most people would not expect a `null` value to be converted to a `NaT`. A field that is a union of `null` and some other type is typically referred to in avro as an optional field. There would be no way when reading an avro file to distinguish between a field that is optional and one that could have a `NaT`.

**Comment by simonejsing** [comment]
Thanks for the very helpful feedback

**Comment by simonejsing** [comment]
After digging a bit further I found a simple work-around, replace all NaN (which must then implicitly include NaT) with None using:

`df = pd.DataFrame(df).replace({np.nan:None})`

Then fastavro will successfully serialize the NaT values as null's.

**Comment by simonejsing** [comment]
Yes, but writing them as Null/None is my expected behavior, so this works for me.

I found an issue though, the replace changes the data type so pandavro fails to interpret the schema.

The correct work-around is:
```
schema = pdx.__schema_infer(df)
df = df.replace({np.nan:None})
pdx.to_avro('temp.avro', df, schema=schema)
```
