### ISSUE TITLE
Handling of "null" type

### ISSUE THREAD

**Issue by norim13** [fastavro/fastavro#320]
I'm having some doubts about how fastavro should handle `null` type. 

I currently use the [avro](https://pypi.org/project/avro/) python lib, and null fields are interpreted as optional. For example, if I have a field that has a type such as `"type": ["null", "integer"]`, the field would be valid if it was either (1) null, (2) integer, or (3) not present. fastavro's validation doesn't contemplate case (3), and requires null fields to be present.

The [official avro schema documentation](https://avro.apache.org/docs/1.8.2/spec.html#schema_primitive) is pretty concise about null fields:

> null: no value

This may be a bit ambiguous, but I believe that it's pretty legitimate that "no value" can mean the absence of the field.

What do you think?

**Comment by scottbelden** [comment]
I'm going to close this in favor of discussion on https://github.com/fastavro/fastavro/issues/292 which I believe is the same topic (though I am currently of the feeling that an explicit `None` value (or using a default value) should be required instead of allowing no value to mean `None`). I have an example there of why I think it should be more explicit as well as a link to an Avro Jira ticket that is kind of related.

Another example where this can be confusing is shown in this issue: https://github.com/fastavro/fastavro/issues/272. In that case, you wouldn't know if `{'foo': 'this is an instance of schema A'}` was an `A` record (because `foo` is set) or a `B` record (because a missing `bar` is okay).
