### ISSUE TITLE
Please support JSON encoded AVRO output format

### ISSUE THREAD

**Issue by ghost** [fastavro/fastavro#33]
https://avro.apache.org/docs/1.7.7/spec.html#json_encoding

**Comment by tebeka** [comment]
Thanks for reporting, I'll take a look.

**Comment by tebeka** [comment]
Sorry for the long delay. How does the current JSON output differ from what's in the spec?

**Comment by tebeka** [comment]
@fcntl Any input on this?

**Comment by mvallebr** [comment]
Could you please consider this example: http://mail-archives.apache.org/mod_mbox/avro-user/201804.mbox/browser

The output differs from what's specified in json_encoding for union types, for instance. 
From https://avro.apache.org/docs/1.7.7/spec.html#json_encoding:

> For example, the union schema ["null","string","Foo"], where Foo is a record name, would encode:
> 
> - null as null;
> - the string "a" as {"string": "a"}; and
> - a Foo instance as {"Foo": {...}}, where {...} indicates the JSON encoding of a Foo instance.

Also, I would expect to be able to write a python dict using `writer` or `schemaless_writer` the same way it's specified in json encoding. This is not the behavior currently.

**Comment by mvallebr** [comment]
> it sounds like you are requesting that they change the specification of JSON encoding

No, not at all, the specification is fine and if followed, it's not ambiguous. What I was requesting them was to change the python library implementation, which doesn't implement JSON encoding specification. 

> Currently, fastavro doesn't implement the JSON encoded avro, but if it did I think it would have to go by what's in the specification.

I couldn't agree more. What I want is the specification implemented.

What can I do to help on this? I have a lot of interest on using an avro library that implements it. I wouldn't like to create a wrapper library on top of neither avro nor fastavro, as I think the base library should support it. 

If you're willing to implement it on a timely manner, I can probably find a way of contributing with tests and test automation. Otherwise, directions on how to contribute with the full feature would also be welcome. I need a library implementing this and I would be very happy if this library is fastavro.

**Comment by mvallebr** [comment]
@scottbelden Did you understand the difference between what we currently have implemented and what is needed?

If you could, please, point me some parts of code I should start looking for to add a failing test case, I could start by contributing to that. With some example test cases failing, I think it should be easier either for you to implement the solution or for me to try to contribute to it.

**Comment by scottbelden** [comment]
Okay. This all sounds good then. This seems like it might be a bit of a lift, so I can try to take a stab at it while I'm at PyCon (about a week and a half from now), but I doubt I'll be able to give it the needed time before then.

As for testing, I guess first we need to decide the interface. I'm assuming we'll need a new `json_reader` and `json_writer` (alternative names could be `json_decoder` and `json_encoder` or maybe something else?).

I think the signatures could be the following:

```python
json_writer(fo, schema, records):
    ...

json_reader(fo, schema):
    ...
```

And I imagine they should be able to be used in the same way as the current reader/writer:

```python
with open(filename, 'w') as fp:
    json_writer(fp, schema, records)

with open(filename, 'r') as fp:
    read_records = json_reader(fo, schema)
```

As for tests, we'd probably want something like this type of test (https://github.com/tebeka/fastavro/blob/master/tests/test_fastavro.py#L63-L94) that reads an existing JSON encoded file and makes sure that it can be read. Beyond that, I'm thinking there is probably an elegant way to have the current [`roundtrip`](https://github.com/tebeka/fastavro/blob/master/tests/test_fastavro.py#L32-L39) helper do both the binary and json roundtrip so that we can leverage a lot of the existing tests. Perhaps something like this:

```python
def roundtrip(schema, records):
    new_file = MemoryIO()
    fastavro.writer(new_file, schema, records)
    new_file.seek(0)

    reader = fastavro.reader(new_file)
    new_records = list(reader)

    json_file = MemoryIO()
    fastavro.json_writer(json_file, schema, records)
    json_file.seek(0)

    reader = fastavro.json_reader(json_file, schema)
    json_records = list(reader)

    assert new_records == json_records

    return new_records

```

What are your thoughts about the above?

**Comment by mvallebr** [comment]
Hey @scottbelden , thanks a lot for your answer!
I will analyze carefully this soon and try to agree on an interface with you here, but what you wrote seems ok, I think the interface, ideally, should be as close as possible to the current one. 

As I have to solve my internal problem here really quickly, I am creating a wrapper library on my own and it's almost finished. When I finish, I will have several test cases for complex scenarios internally here and all I will have to do is replacing my wrapper by the new version of fastavro. 

I will take some weeks before prioritizing contributing to this, but I will definitely do it. Sorry for the delay to reply!

**Comment by scottbelden** [comment]
I might have some time in the coming days to take an initial stab at this. If you are able to post your wrapper library when it's in good shape then that could be helpful in implementing this. Otherwise I'll see what I can come up with on my own.

**Comment by mvallebr** [comment]
Ok, I won't have time to contribute with much, and I have had several problems trying to run the tests. 

I created a docker file on my branch, made sure all tests were passing and then I made them fail by creating some tests:

https://github.com/tebeka/fastavro/compare/master...mvallebr:master?expand=1

You probably won't find many things useful, but I hope at least the basic scenarios are useful. In my usecase, I use only schemaless methods, so actually this interface should also be changed. 

To run tests on my fork, I just do `docker build .`. I am not sure what to configure to have tox tests passing, and I am not sure where to ask as well.

**Comment by mvallebr** [comment]
I've updated the test case at https://github.com/tebeka/fastavro/compare/master...mvallebr:master?expand=1 to a more complete example

**Comment by scottbelden** [comment]
@mvallebr I created an initial draft of this that is [here](https://github.com/tebeka/fastavro/pull/188). It won't work with logical types, and I'm not sure if I'm going to keep the implementation, but I just wanted to throw together something really simple to start with.

If you have time and would like to try it out I'd be interested in hearing your feedback.

Also, I haven't set up a java environment to make sure that the json is the same that the java side would create, but I'm pretty sure I followed the spec correctly.

**Comment by mvallebr** [comment]
I will add comments right away

**Comment by Artimi** [comment]
Hi, is there any update on this? I think this could resolve issue https://github.com/fastavro/fastavro/issues/191 which is blocker for us.

**Comment by mvallebr** [comment]
Guys, I am really sorry I haven't got in touch more - I really wanted to contribute to this project instead of creating a wrapper and I hope the company I was working for do it some day, but I haven't got the approval internally and I forgot to reply back here, I am really sorry. 

I saw the PR and I think it looks good the way it is. Maybe it could be even better in the future, but I personally see no reason to not approve this - the only thing I was going to add more were tests, but it's much better to have this with limited tests than not having it. 

Once again, I am really sorry for the lack of reply :(

**Comment by scottbelden** [comment]
I'll try to find some time to take another look at that PR. Personally I don't really like it because it duplicates a lot of logic that already exists. At one time I looked into how the java reference implementation handles de-duplication of the logic and attempted to implement that [in a branch](https://github.com/fastavro/fastavro/compare/issue33_take2). However, I wasn't really satisfied with that either.

I think you all are right that getting https://github.com/fastavro/fastavro/pull/188 into shape to be merged is probably the best way forward for the moment. The more complicated parser approach is useful if there are future encoders/decoders (e.g., imagine something to/from YAML), but is probably overkill right now.

**Comment by scottbelden** [comment]
@Artimi Would you be able do a test run of https://github.com/fastavro/fastavro/pull/188 and see if it works for you. I'd be interested in getting some feedback before fully merging it. If it would be easier, I could make a pre-release that could be installed.

**Comment by Artimi** [comment]
I have a few remarks:

1. As @mvallebr wrote https://github.com/fastavro/fastavro/pull/188/files#r188304915 this implementation will suffer from ambiguous records. Right now we are working this around by using tuple `(schema, datum)` as `union` element https://github.com/fastavro/fastavro/blob/master/fastavro/_write_py.py#L307 and we would not be able to use it before this functionality.
2. We are also using logical types including custom like described here https://github.com/fastavro/fastavro/issues/173#issue-315762591. Unfortunately, we would not be able to use `fastavro` without logical types.

The reason why we would like to use JSON encoding is to get rid off ambiguity. Currently, we are using a hack described here https://github.com/fastavro/fastavro/issues/191#issuecomment-443128258 with older version of fastavro and we would like to move on.

So as for me, I believe that #188 is a good start but unfortunately we won't be able to use it yet.

**Comment by scottbelden** [comment]
I think solving the ambiguous records in a performant way will be challenging. I believe the last time I looked into it, having wrapper classes instead of plain python dictionaries definitely slowed down the cython performance.

I can add in the support for logical types, but it sounds like that still wouldn't be sufficient for your purposes. Is that right?

**Comment by Artimi** [comment]
Yes, we probably won't be able to use it now. So maybe we can merge it now and prepare two new issues for data ambiguity and adding/refactoring of logical types. What do you think?
