### ISSUE TITLE
Extracting all names, types for coercion

### ISSUE THREAD

**Issue by yiga2** [fastavro/fastavro#375]
We get data from `xmltodict` where all dict values are set as string. I like to parse each nested dict and cast the values based on the target avro schema.

I see a few helper functions in `schema` module that could help but not sure how to traverse easily. I could write a dedicated function to do so but fastavro could best handle the coercion directly in the `prepare_xxx` functions - this would save from parsing twice.

Thoughts ?

**Comment by scottbelden** [comment]
Are you suggesting this only for logical types? They are the only ones that use those `prepare_xxx` functions.

In general I'm not sure about this. In specific cases like https://github.com/fastavro/fastavro/issues/334 I think it's fine to accept a string instead of a datetime object because I think it's pretty common to represent a time as a string. However, I'm not sure that it's as common to represent, for example, a decimal type as a string.

**Comment by yiga2** [comment]
I am suggesting coercion for any type and that the feature be included in the Cython module. 

`string` is the only valid value type possible if a dict was build without the understanding of a schema. `xmltodict` produces such dict but I am sure there are others.

Up to vote I guess but we could have an optional arg in the writer for that e.g. `strict_types` = default `True`

**Comment by scottbelden** [comment]
I don't think this would work well for something like a field that is a union of a string and integer. If the value were `"0"` it would be impossible to know if it should be left as the string zero or coerced to the integer zero.

I'd also have to see how this affects performance in the normal case where the coercion isn't needed.

**Comment by yiga2** [comment]
I understand - we were thinking of converting upstream using the avro schema as model (xmltodict has a postprocessing feature) but that would slow things down (too). 
Instead we serialize all as-is, as strings, and load and cast when needed in BigQuery.
