### ISSUE TITLE
Failing tests on a clean ubuntu setup

### ISSUE THREAD

**Issue by mateuszmrozewski** [fastavro/fastavro#408]
Steps to reproduce:

1. Spin up a new Ubuntu (I use a VM with Ubuntu 18.04)
2. Install python
3. Clone fastavro
4. Create virtual environment
5. Install dependencies using `pip install -r developer_requirements.txt`
6. Run test using run-tests.sh

Expected result:
All tests pass

Actual result:
A few tests fail due to missing lz4, zstandard, snappy. I had to install those packages on top of the developer_requirements.txt. This also required installing some ubuntu packages.

For the missing dependencies, should they be added to developer_requirements.txt?

**Comment by scottbelden** [comment]
Maybe I should document that those tests are expected to fail unless you go about installing the other dependencies. I don't think this is too much of a problem though because when the tests run on CI the dependencies are installed (or for windows the tests are skipped because installing the snappy dependencies was not obvious to me).

However, I agree that this is probably confusing and that it should be documented.

**Comment by mateuszmrozewski** [comment]
Is there any downside of adding them to developer_requirements.txt? I think that would be the easiest.

**Comment by scottbelden** [comment]
That might work for lz4 and zstandard but I think the snappy test might still fail because it needs more than just the python package

**Comment by mateuszmrozewski** [comment]
Yes, it will need some development system packages. I think that is ok. I would only expect that after running `pip install -r developer_requirements.txt` there are no python packages left to be installed.

**Comment by scottbelden** [comment]
I have a PR to address this: https://github.com/fastavro/fastavro/pull/413

However, I still chose to keep snappy out of the `developer_requirements` since it isn't as trivial as the others to install. I did include a note in the testing section of the README to mention that it's normal for some tests to fail.
