### ISSUE TITLE
Python 2 incompatibility

### ISSUE THREAD

**Issue by Nicusor97** [fastavro/fastavro#467]
Hello, 

There seems to be an issue with the latest version of fastavro (1.0) on Python 2 after you dropped the Python 2 support from what I saw in your Changelog. Here is the error that I have when trying to install fastavro on Python 2 : 
```
if sys.implementation.name != "pypy":
     AttributeError: 'module' object has no attribute 'implementation'
```
You dropped Python 2 support but you forgot to add `python_requires='>=3.5'` in your setup.py that will prevent users with Python 2 from downloading a sdist version they cannot build. 

For more information about python_requires you can check the following details: 
Note: supporting python_requires requires setuptools>=24.2.0 and pip>=9.0.0 to benefit from it.
Details here: https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires

**Comment by Nicusor97** [comment]
I already created a new PR to fix this : #466

**Comment by scottbelden** [comment]
Whoops. I remember thinking about this at one point, but I guess I never put it in.

Do you happen to know what will happen to Python 2 people if I merge this and release it as `1.0.1`? Will `pip` just fall back to `1.0.0` for them and end up with the same problem?

**Comment by scottbelden** [comment]
Perhaps a post release can fix this. I'm still trying to verify that if I create a `1.0.0.post1` that pip will not try to fall back to `1.0.0`

**Comment by scottbelden** [comment]
So I don't think there is a clean way to do the fall back (at least I haven't thought on one yet). Even if we add the `python_requires`, I still get `ERROR: Package 'fastavro' requires a different Python: 2.7.17 not in '>=3.5'` when trying to install. I think this is because the [setup.py we have still uses `setup_requires` which it seems invokes `easy_install` and causes the error](https://github.com/pypa/pip/issues/6667#issuecomment-507164431).

I know `pyproject.toml` is supposed to be the way to fix this, but I'm not sure if it's possible to define dependencies in that file based on the python implementation (i.e. pypy vs cpython).

Given all of this, unless there is a cleaner way, perhaps an option would be to just create a custom error message for Python 2 to indicate that they should install `fastavro<=1.0.0`

**Comment by scottbelden** [comment]
Actually, perhaps it is possible to use pyproject.toml to define what we want similar to how it is done here: https://github.com/scikit-learn/scikit-learn/blob/2225f0ad35e757f156e19cac46918335ef16aa6b/pyproject.toml#L7

**Comment by Nicusor97** [comment]
Honestly, not sure why the pip install command still failed after you added python_requires in your setup.py. What versions of setuptools and pip are you using ? I left a note in my PR : 
```
Note: supporting python_requires requires setuptools>=24.2.0 and pip>=9.0.0 to benefit from it.
Details here: https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires
```
For all the python modules where I did this change everything was well after a new release. I will try to reproduce what you tried on my side also and keep you posted.

**Comment by scottbelden** [comment]
In my python 2 environment I have setuptools 41.6.0 and pip 20.2.2.

Here's what I did to test:

1. Manually edit the setup.py with the following changes:

```diff
diff --git a/setup.py b/setup.py
index c83d168..57425af 100644
--- a/setup.py
+++ b/setup.py
@@ -32,6 +32,7 @@ if not hasattr(sys, 'pypy_version_info'):


 def version():
+    return "1.0.0.post1"
     pyfile = 'fastavro/__init__.py'
     with open(pyfile) as fp:
         data = fp.read()
@@ -55,7 +56,7 @@ if not hasattr(sys, 'pypy_version_info'):
     setup_requires += cpython_requires

 tests_require = ['pytest', 'flake8', 'check-manifest']
-if sys.implementation.name != "pypy":
+if sys.version_info >= (3, 0) and sys.implementation.name != "pypy":
     tests_require.append('mypy')

 setup(
@@ -95,6 +96,7 @@ setup(
         'Topic :: Software Development :: Libraries',
         'Topic :: Scientific/Engineering :: Information Analysis',
     ],
+    python_requires='>=3.5',
     extras_require={
         'codecs': ['python-snappy', 'zstandard', 'lz4', 'backports.lzma'],
         'snappy': ['python-snappy'],
```

2. Build a new release with `FASTAVRO_USE_CYTHON=1 python setup.py sdist`. I did this in a Python 3.7 environment.

3. In the Python 2 environment, uninstall fastavro and then try to install using the following: `pip install -f dist --no-cache -U fastavro`. This is what is output:

```
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Looking in links: dist
Processing ./dist/fastavro-1.0.0.post1.tar.gz
ERROR: Package 'fastavro' requires a different Python: 2.7.17 not in '>=3.5'
```

**Comment by scottbelden** [comment]
So I tried merging the PR and creating a `1.0.0.post` release. I thought the idea of the post release was to effectively shadow the `1.0.0` release, but that doesn't seem to happen. When I try to install on Python 2, `pip` skips the `1.0.0.post` as expected because of the `python_requires`, but it still just tries to use the `1.0.0` tarball.

I could delete the `1.0.0` tarball from pypi... I'm a little worried about doing that as it sometimes causes issues for people that run their own mirrors or have the cached `1.0.0` version, but leaving it up also seems like a bad idea because now anyone on Python 2 that tries to install will hit an error at install time.

**Comment by scottbelden** [comment]
Okay, so I learned that there is a new `yank` feature on pypi which looks like it will do what I want. It effectively hides the `1.0.0` release so that it won't be used by `pip` but is still technically installable if someone does `pip install fastavro==1.0.0`.

I was able to install correctly on Python 2 now:

```
pip install -U --no-cache fastavro
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting fastavro
  Downloading fastavro-0.24.2-cp27-cp27m-macosx_10_14_x86_64.whl (465 kB)
     |████████████████████████████████| 465 kB 804 kB/s
Requirement already satisfied, skipping upgrade: pytz in ... (from fastavro) (2020.1)
Installing collected packages: fastavro
Successfully installed fastavro-0.24.2
```

**Comment by Nicusor97** [comment]
Thank you so much for your work to fix the problem with this module on Python 2 ! Right, the `yank`  feature fixed the issue.
