### ISSUE TITLE
recursively loading referenced schemas returns union instead of single schema

### ISSUE THREAD

**Issue by venthur** [fastavro/fastavro#476]
Version: `fastavro==1.0.0.post1`

When recursively loading referenced schemas using `schema.load_schema`, I get the equivalent of a Union of all involved schemas instead of the "Parent" schema only. Technically, I get a `list` of schemas back in this case.

This is probably a bug as it allows me to serialize Parent **and** Child records whereas I'd expect to be able to only serialize Parent records.

Here's a simple test case to reproduce:

`Parent.avsc`:
```json
{
    "type": "record",
    "name": "Parent",
    "fields": [
        {
            "name": "child",
            "type": "Child"
        }
    ]
}
```

`Child.avsc`
```json
{
    "type": "record",
    "name": "Child",
    "fields": [
        {
            "name": "id",
            "type": "int"
        }
    ]
}
```

`test_parent_child.py`
```python
from io import BytesIO

from fastavro.schema import load_schema
from fastavro import schemaless_writer

schema = load_schema("Parent.avsc")

child_record = {'id': 2}
parent_record = {'child': child_record}

# ok
new_file = BytesIO()
schemaless_writer(new_file, schema, parent_record)

# this should not work
new_file = BytesIO()
schemaless_writer(new_file, schema, child_record)
```

Some other functions like `schema.fullname(schema)` also break in that case as they expect a `dict` and not a `list`.

**Comment by scottbelden** [comment]
> I get the equivalent of a Union of all involved schemas instead of the "Parent" schema only

I think I agree that this is a bit confusing. If the initial schema is a single dictionary then the result should probably be a single dictionary. Likewise, if the initial schema is a union then the result should probably be a union.

I think the current behavior was probably a result of an easier implementation. To have the more correct behavior, we would need to make sure to inline the dependency schemas in the right places.

If you'd like to take a stab at a PR, feel free to do so. Otherwise I'll try to get to it at some point.

**Comment by scottbelden** [comment]
Note to self...

We would want to test these scenarios:

- Schema A depends on B and C; Schema B depends on C
- Schema A depends on B and C; Schema C depends on B

**Comment by venthur** [comment]
I'm not sure if it is allowed to expand the same named type more than once. I.e. if in my example above `Parent` had **two** `Child`s as defined in `Child.avsc`. Should both occurrences be expanded or only the first?

Expanding only the first occurrence seems quite tricky with the current recursive approach.

**Comment by scottbelden** [comment]
You are right that it would be invalid to expand both. Only the first should be expanded. I agree that expanding only the first is tricky (and why the currently implementation is as it is because of the simpler logic), but as long as the top level schema is recursively expanded in a depth first manner, I believe it should work.

For example, take my test scenario of `Schema A depends on B and C; Schema B depends on C`:

We would start loading A. Then we would get to the schema B, realize we haven't loaded it, and load it. When we load B, it depends on C, so we would load that. Then we would get back to parsing A, see that it depends on C, but since we've already loaded C we can just keep it as the short namespace reference rather than replacing it with the full C schema.

This is probably a bit confusing with just this block of text and no actual example A, B, and C files so maybe when I have a few more minutes I can post a better example.

**Comment by venthur** [comment]
I suspect the bug is hiding in this block: 
https://github.com/fastavro/fastavro/blob/f468264b0f86661f1893c8b32bc592fb44e39c75/fastavro/_schema.pyx#L301-L318
where basically all four combinations of `schema: list|dict`, `sub_schema: list|dict` are evaluated. In all four cases we call `_load_schema` again with a `list` as the new schema to evaluate, however at least when the `schema` was a dict, we probably need to insert `sub_schema` at the appropriate place and call `_load_schema` with a `dict` instead.

Furthermore, I suspect that not all four combinations make sense, IMHO the `sub_schema` should never be a `list` but something that can be inserted directly into the `schema`. I.e. `sub_schema` is always a schema that got recursively loaded from file when the named type could not be found, shouldn't this always be a `dict` then?

**Comment by scottbelden** [comment]
I think you are probably right about the fact that `sub_schema` should not be a list. It currently can because of the way we turn the individual schemas into a union of schemas, but if the we change things to do the correct inserts in place then I think it should always be a dictionary.
