### ISSUE TITLE
Default values do not work when reading from an avro-json format

### ISSUE THREAD

**Issue by marcosschroh** [fastavro/fastavro#485]
Defaults values when using binary `avro-json` format raise an exception.

Schema:

```python
schema = {'type': 'record',
 'name': 'User',
 'fields': [{'name': 'name', 'type': 'string'},
  {'name': 'age', 'type': 'long'},
  {'name': 'pets',
   'type': {'type': 'array', 'items': 'string', 'name': 'pet'}},
  {'name': 'accounts',
   'type': {'type': 'map', 'values': 'long', 'name': 'account'}},
  {'name': 'favorite_colors',
   'type': {'type': 'enum',
    'name': 'favorite_color',
    'symbols': ['BLUE', 'YELLOW', 'GREEN']}},
  {'name': 'country', 'type': 'string', 'default': 'Argentina'},
  {'name': 'address', 'type': ['null', 'string'], 'default': None}],
 'doc': 'An User',
 'namespace': 'User.v1',
 'aliases': ['user-v1', 'super user']}
```

Value to decode: 

```python
data = b'{"name": "MgXqfDAqzbgJSTTHDXtN", "age": 551, "pets": ["aRvwODwbOWfrkxYYkJiI"], "accounts": {"DQSZRzofFrNCiOhhIOvX": 4431}, "favorite_colors": "GREEN",  "address": {"string": "YgmVDKhXctMgODKkhNHJ"}}'
```

Steps:

```python
import io
import fastavro

input_stream = io.StringIO(data.decode())
records = fastavro.json_reader(input_stream, schema)

payload = list(records)[0]

# throws exception "KeyError: 'country'"
```

For the complete example go here: https://github.com/marcosschroh/dataclasses-avroschema/issues/82

**Comment by scottbelden** [comment]
I wanted to pull @FreCap into this discussion since they were the one that opened the initial issue in the other repo.

@FreCap How did you create the initial value to decode? Was it created with the `json_writer` and with the same schema? Default values are usually used for schema evolution which the json reader doesn't support right now (the only schema that can be provided is the writer schema).

A [similar issue was filed in the main Avro issue tracker](https://issues.apache.org/jira/browse/AVRO-2890) (so I don't believe something like this even works currently for the Java reference implementation. One of the suggestions there was to use the default value if it came across a field which was missing from the data. Another option I can think of would be the more avro-style approach and allow the user to specify the original writer schema as well as the new reader schema so that schema evolution can happen like normal.

**Comment by marcosschroh** [comment]
@scottbelden The default value is the approach that we are following here. As you can see, the value to be decoded does not  includes the field country, and the schema has it with a default value as `None`,  so `fastavro` should be able to decoded it.

**Comment by scottbelden** [comment]
This should be resolved in the next release which I'll try to get out today or tomorrow.
