### ISSUE TITLE
Compile schemas into executable code objects

### ISSUE THREAD

**Issue by spenczar** [fastavro/fastavro#505]
Warning: slightly crazy ideas ahead.

In the course of working through the hand-written decoder in #503, I got to thinking about the structure of fastavro's parsing. When it is reading a deep union or record, it needs to do a bunch of bookkeeping and dictionary lookups and function calls and stuff to make sense of things. If you were writing the deserialization function by hand for a specific schema, that's not how you'd do it; you'd directly call `read_utf8` and then `read_long` and then `read_long` and then `read_bool` or whatever - you'd know just the right order to call them and wouldn't need to look anything up.

But of course, you can't do that for the generic case of a deserializing library that doesn't know the schema ahead of time.

Or can you? Python has the `compile` and `eval` builtins. You _could_ parse the schema into a big string which is the Python code you would have hand-written. You could compile and evaluate that string, and then invoke the resulting code object to actually do parsing. You only need to compile the schema once, and then invoke the code object each time you want to parse with that schema.

I have a proof of concept of this. For my weird astronomical alerts, it is about 20-30% faster than fastavro's  `reader`. 

The compiler POC is here: [schema_compile.py](https://github.com/ZwickyTransientFacility/alertbase/blob/322f8a67dc6cff68e553c25ad1f3bc1b688199bd/src/alertbase/schema_compile.py). For debugging, I printed out the code object it generates, which you can find [here](https://github.com/ZwickyTransientFacility/alertbase/blob/322f8a67dc6cff68e553c25ad1f3bc1b688199bd/gen.py) - it's nasty but it works.

Using the same benchmarks as #503, I ran some numbers:

method | Single-file time (ms) | Tarball time (per object) (ms) | Tarball MB/sec |
| ------ | ----- | ----- | ----- |
compiled | 0.661| 1.210 | 54.84 |
fastavro | 0.903 | 1.546 | 42.90 |
avro | 5.883 | 6.914 | 9.59 |

(I've omitted the subschema and "manual decoder" cases because they're not relevant here; the compiled schema parses _all_ fields).

My code is not perfect by any means - it's just a hacky proof of the idea: 
- I didn't implement `fixed` or `map` types, because they aren't in my schema.
- Lots of the generated code is dead code; there is a lot that could be optimized away.
- I don't think I handle some weird cases right, like arrays-of-arrays. I definitely don't handle recursion right.
- I do no error handling or sanity checks or anything, so corrupted data would probably go haywire.

Those seem like things we could overcome. A more serious issue is that stack traces are pretty inscrutable with this method. I don't know if there's a way to make things better, there. It could be confusing to people. But this could be kind of similar to how C code works in Python anyway.

What do you think? If you're interested in this idea, I can work on a cleaned-up version in a branch.

**Comment by scottbelden** [comment]
This is an interesting approach and it certainly seems worth exploring. The idea of parsing the schema once and building up the code path reminds me of some of [the design ideas from a competing avro library](https://github.com/pluralsight/spavro). Though I never really took the time to fully grasp the way that library would build up the execution.

The idea of writing out the string form of the code and then executing it does seem a bit scary and it seems like it could make debugging difficult, but I'd have to try it to see how it would work.

I like the idea and with the number of tests I think it's possible to make a change like this that changes a lot of the internals and have a pretty high confidence that it would work correctly. However, it would probably be something that might take a decent bit of time to implement, debug, and get to a point where I feel confident in being able to maintain it. So if this is something you'd want to be able to use for your project in the near term, you may need to maintain your own fork/version.

That being said, if you'd like to take an initial stab at an implementation, that would certainly be appreciated. Otherwise I'll try to find some time to take your initial thoughts work them in. But since this does sound like a fairly big change to the internals, I can't guarantee that it will be merged in until I've had a chance to get my hands dirty with it.

**Comment by spenczar** [comment]
That is a very reasonable response. I think I'll hack around with this idea in a fork for a little while, and see how it performs in low-stakes, experimental settings. I'll post here when I have something that runs through tests, checks error cases, etc.

An interesting thing I just discovered: the Java Avro library does runtime code generation with big templates, very similar to my proposal, but guarded by a build-time flag; developers opt-in by setting a property on their build. It was added here: https://github.com/apache/avro/pull/350. They also had the smart idea of pre-validating that a schema _can_ be compiled into bytecode, and only attempting to do so when it looks possible (see [here](https://github.com/apache/avro/pull/350/files#diff-fede5c0d5b5d2807bb6ed13381eb0d9d443fe6c66f0651db2d376f854a8f9503R762)), which I really like as a way to gradually build this feature. For example, recursive schema definitions are really obnoxious to support, so maybe we just... don't?

Maybe there's some similar way fastavro could let users opt in to this experimental approach - just a thought.

**Comment by spenczar** [comment]
I have spun this off into a separate project, https://github.com/spenczar/avroc. Thanks for thinking it through with me and exploring the design - I really appreciate it.

**Comment by scottbelden** [comment]
Sorry that I didn't feel like I could merge it in here but I'm glad you were able to get it working!

**Comment by Artimi** [comment]
Hi, we did kinda a similar thing but instead of generating Python code we generate Cython to get an extra speed. The tool is called Cerializer https://gitlab.com/quantlane/libs/cerializer and was crafted for our purposes. To make it work you need to compile the schema before using but then it resolved in twice faster de/serialization.
