### ISSUE TITLE
Document custom logical types

### ISSUE THREAD

**Issue by scottbelden** [fastavro/fastavro#514]
[As mentioned here](https://github.com/fastavro/fastavro/issues/513#issuecomment-794096900), we should add some documentation on how to create custom logical readers and writers. This should include:

- Function signature for the reader function
- Function signature for the writer function
- What to name the logical type and what key to use when specifying the custom logical functions

**Comment by FreCap** [comment]
Can we add in the function signature also ` **kwargs` for forward compatibility?

Since the logicalType parsers/preparers are exposed, if we add a new parameter in the signature in fastavro, we will break all of them until they update them. However if ` **kwargs` is in the signature by default, it shouldn't break.

One parameter that I would like to add for example is `is_validate` to understand if the logical_writer is being called by the writer or validator:
- the validator can be more strict
- the writer could be more allowing (returning the same value if it is not of a instance that it can handle)

**Comment by FreCap** [comment]
> > Can we add in the function signature also **kwargs for forward compatibility?
> 
> I don't think anything in the codebase needs to change to support this. Right now it is possible to define the reader/writer functions with `*args` and `**kwargs` for forward compatibility as seen in `prepare_read` here: [#513 (comment)](https://github.com/fastavro/fastavro/issues/513#issuecomment-793914732)

I agree, this is probably matter more about documentation that actual code base, and calling out that this approach is suggested


> The current logical writer functions don't have strong checks on the input data being provided. For example, take a look at `prepare_date`:

Yes, I agree this is the current behavior. Since the avro can then be processed in many different ways, we don't know what kind of error could come up (what about if somebody just stores it without the serializer assuming that it is validated).

For this reason having a parameter that tells us if we are "validating" or not the input could be helpful to decide if we want a stricter approach.

Do other avro implementations allow to have `validate(x) == success` if a parameter is supposed to be a string and instead it is a integer?

**Comment by scottbelden** [comment]
> Do other avro implementations allow to have validate(x) == success if a parameter is supposed to be a string and instead it is a integer?

I think this probably depends on the implementation. In a statically typed language something like this might get caught by default. In this library, validation is not done by default and I think it would add a non-significant amount of overhead.

Many of these potential type errors do naturally bubble up, but they can sometimes get exposed as unhelpful tracebacks. For example, here's an example if we try to write an `int` to a `string` schema:

```python
import io
import fastavro
from fastavro import writer
writer_schema = fastavro.parse_schema("string")

bio = io.BytesIO()

writer(bio, writer_schema, [1])
```

```python
  File "fastavro/_write.pyx", line 688, in fastavro._write.writer
    output.write(record)
  File "fastavro/_write.pyx", line 641, in fastavro._write.Writer.write
    write_data(self.io.value, record, self.schema, self._named_schemas, "")
  File "fastavro/_write.pyx", line 353, in fastavro._write.write_data
    return write_utf8(fo, datum)
  File "fastavro/_write.pyx", line 128, in fastavro._write.write_utf8
    b_datum = datum.encode()
AttributeError: 'int' object has no attribute 'encode'
```

However, there is a `validator` option that can be provided to the `writer` to force validation. So if we change that example from `writer(bio, writer_schema, [1])` to `writer(bio, writer_schema, [1], validator=True)` then we get this:
```python
  File "fastavro/_write.pyx", line 688, in fastavro._write.writer
    output.write(record)
  File "fastavro/_write.pyx", line 640, in fastavro._write.Writer.write
    self.validate_fn(record, self.schema, self._named_schemas)
  File "fastavro/_validation.pyx", line 177, in fastavro._validation._validate
    cpdef _validate(
  File "fastavro/_validation.pyx", line 254, in fastavro._validation._validate
    raise ValidationError(ValidationErrorData(datum, schema, field))
fastavro._validate_common.ValidationError: [
  " is <1> of type <class 'int'> expected string"
]
```

And yes, there are some instances where the library won't catch the wrong type. For example, if we try to write a `string` to a `boolean` it will just work:

```python
import io
import fastavro
from fastavro import writer, reader, validate

writer_schema = fastavro.parse_schema("boolean")

bio = io.BytesIO()

writer(bio, writer_schema, ["A"])

bio.seek(0)

for record in reader(bio):
    print(f"Reading the record returns: {record}")
    # Reading the record returns: True
```

But if we use the `validator=True` again, then we have the strong check:

```python
  File "fastavro/_write.pyx", line 688, in fastavro._write.writer
    output.write(record)
  File "fastavro/_write.pyx", line 640, in fastavro._write.Writer.write
    self.validate_fn(record, self.schema, self._named_schemas)
  File "fastavro/_validation.pyx", line 177, in fastavro._validation._validate
    cpdef _validate(
  File "fastavro/_validation.pyx", line 254, in fastavro._validation._validate
    raise ValidationError(ValidationErrorData(datum, schema, field))
fastavro._validate_common.ValidationError: [
  " is <A> of type <class 'str'> expected boolean"
]
```

Does using this `validator=True` option solve the concern?

**Comment by scottbelden** [comment]
Resolved via https://github.com/fastavro/fastavro/commit/17724695b52208e4a3a68eeef990e39cf0d2e466
