### ISSUE TITLE
Unable to write optional arrays if the array is represented by a tuple

### ISSUE THREAD

**Issue by choogeboom** [fastavro/fastavro#548]
When parsing a union, fastavro is unable to distinguish between an array stored as a tuple, and the [tuple notation used to specify which branch of a union to take](https://fastavro.readthedocs.io/en/latest/writer.html#using-the-tuple-notation-to-specify-which-branch-of-a-union-to-take).

Example
---

```python
from io import BytesIO
from fastavro import writer

schema = {
    "type": "record",
    "name": "Foo",
    "fields": [
        {
            "name": "foo", 
            "type": ["null", {"type": "array", "items": "int"}]
        }
    ]
}

records = [{"foo": (1, 2, 3)}]

fo = BytesIO()
writer(fo, schema, records)
```

The code above results in the following error:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "fastavro/_write.pyx", line 726, in fastavro._write.writer
  File "fastavro/_write.pyx", line 679, in fastavro._write.Writer.write
  File "fastavro/_write.pyx", line 419, in fastavro._write.write_data
  File "fastavro/_write.pyx", line 363, in fastavro._write.write_record
  File "fastavro/_write.pyx", line 417, in fastavro._write.write_data
  File "fastavro/_write.pyx", line 253, in fastavro._write.write_union
ValueError: too many values to unpack (expected 2)
```

This is due to the following line: https://github.com/fastavro/fastavro/blob/e082ba399e0c4cb85dbf6d6505742b271e3e1e34/fastavro/_write.pyx#L252

As a user, I would like to control whether `fastavro` parses tuples as data or meta-data.

**Comment by scottbelden** [comment]
I need to think about this a bit, but if an option existed it would apply to all fields. That is, there wouldn't be a way to say that one field uses the tuple notation and another is just acting as an array.

**Comment by choogeboom** [comment]
An option that shuts off the tuple notation would be great!

Alternatively, you might be able to do some introspection on the schema and tuple in order to infer the correct interpretation, but this seems less likely.

**Comment by scottbelden** [comment]
Yeah, I thought about that, but I don't think there's a way to make it work perfectly. For example, even if we inspected the schema and tuple to make sure that the tuple notation would only be used in cases where:

- The tuple is exactly two items
- The first item is a string that is the name of a type in the union

It would still be ambiguous in cases like the following:

```python
schema = {
    "type": "record",
    "name": "Foo",
    "fields": [
        {
            "name": "foo", 
            "type": ["string", {"type": "array", "items": "string"}]
        }
    ]
}

record = {"foo": ("string", "0")}
```

Now, we could say that in that specific case that if the user really wants an array they need to use a list or some other iterable. This would probably work for 99% of cases seamlessly which maybe is good enough... Though it would be even more confusing for the problem case because no error would occur like it does currently and so someone might not notice that data is getting serialized incorrectly until much later.

**Comment by choogeboom** [comment]
You might be able to make it work if you add a third constraint:

* The second item in the tuple matches the expected schema

But this check could potentially be so expensive as to not be worth it. Probably better to just add an explicit flag to turn off the tuple notation.
