### ISSUE TITLE
Legacy Avro read file support lost in version 1.4.1 onwards

### ISSUE THREAD

**Issue by aserednyakov** [fastavro/fastavro#560]
### Description
I work with Avro files which were generated using a legacy version of fastavro module (ver. 0.21.19). When using the latest few patch releases of fastavro (1.4.1 through 1.4.4), file reads cannot open these legacy files due to a schema parsing error. The reason is due to an assumption in the code: if "__fastavro_parsed" is in the schema, then "__named_schemas" is expected, then accessed using square brackets. In the legacy files, this does not hold true.

### Error
```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "fastavro/_read.pyx", line 1134, in fastavro._read.reader.__init__
  File "fastavro/_read.pyx", line 1106, in fastavro._read.file_reader.__init__
  File "fastavro/_schema.pyx", line 78, in fastavro._schema.parse_schema
KeyError: '__named_schemas'
```

### Proposal
My [proposed change](https://github.com/fastavro/fastavro/pull/559) is simple and I've tested that it works. I have also added a new Avro file to make sure future changes do not break it again accidentally. I'd like to solicit feedback on this proposed set of changes.

### Cause
I looked at the history of the codebase and saw that no Avro files were added since 2017-09-02, which is why my use-case was not caught. Since then, a series of changes were introduced which eventually broke support for legacy files as of version 1.4.1.

Addition of "named_schemas" on this [commit](https://github.com/fastavro/fastavro/commit/7007cbadd5283e1d7c08b0c70e4e3025f849698a) (Jul 29, 2020):
```
if _write_hint:
    # Make a copy of parsed_schema so that we don't have a cyclical
    # reference. Using deepcopy is pretty slow, and we don't need a
    # true deepcopy so this works good enough
    named_schemas[fullname] = {
        k: v for k, v in iteritems(parsed_schema)
    }

    parsed_schema["__fastavro_parsed"] = True
    parsed_schema["__named_schemas"] = named_schemas
```

Then this [commit](https://github.com/fastavro/fastavro/commit/7007cbadd5283e1d7c08b0c70e4e3025f849698a#diff-88da0c6c5366b43a87a45bfded5abec213e6be5f7b8bd8130f7d2d2acf9499f3R72) (July 29, 2020):
```
for key, value in iteritems(schema["__named_schemas"]):
    _named_schemas[key] = value
```

And finally in 1.4.1 this [change](https://github.com/fastavro/fastavro/commit/9aa185041ad194cd71e7e84ec1cfbf957fe092f9#diff-88da0c6c5366b43a87a45bfded5abec213e6be5f7b8bd8130f7d2d2acf9499f3R78) finally broke it unintentionally (order of parsing changed) (May 10, 2021):
```
if isinstance(schema, dict) and "__fastavro_parsed" in schema:
    for key, value in schema["__named_schemas"].items():
        named_schemas[key] = value
```

**Comment by aserednyakov** [comment]
In addition to the issue and proposed solution, could someone please shed some light on what is [this code](https://github.com/fastavro/fastavro/blob/0922a2b4438cc37dae6abd3e43fa02567e2a5ef6/fastavro/_write_py.py#L405-L428) and [this related code](https://github.com/fastavro/fastavro/blob/0922a2b4438cc37dae6abd3e43fa02567e2a5ef6/fastavro/_write.pyx#L637-L658) meant to do and why does it exist for modifying the schema at the top level when writing?

Because of the above linked code, I had to add a (odd looking) modification to the writer_schema in one of the unit tests in order for the tests to pass.

**Comment by scottbelden** [comment]
> In addition to the issue and proposed solution, could someone please shed some light on what is [this code](https://github.com/fastavro/fastavro/blob/0922a2b4438cc37dae6abd3e43fa02567e2a5ef6/fastavro/_write_py.py#L405-L428) and [this related code](https://github.com/fastavro/fastavro/blob/0922a2b4438cc37dae6abd3e43fa02567e2a5ef6/fastavro/_write.pyx#L637-L658) meant to do and why does it exist for modifying the schema at the top level when writing?
> 
> Because of the above linked code, I had to add a (odd looking) modification to the writer_schema in one of the unit tests in order for the tests to pass.

When calling `parse_schema(schema, self._named_schemas)` the original `schema` is modified to have the `__fastavro_parsed` and `__named_schemas` information in that dictionary, but we don't actually want to write that out to the avro file because it would bloat the schema with information that is specific to this implementation and not relevant for the general case avro reader. Therefore, those keys are removed after parsing.

**Comment by scottbelden** [comment]
I wanted to add another test case for a file like yours (that has `__fastavro_parsed` and not `__named_schemas`) but also references those names in multiple fields. In that case, we need to make sure we do actually re-parse the schema. I tried adding to your branch but I don't think I have permissions, so I just created a new branch with your original commit and my commit. The PR is here: https://github.com/fastavro/fastavro/pull/561. If it's easy for you to test that branch with your avro files that would be appreciated, otherwise I'll plan to merge it and make a new release shortly.

Thanks for the detailed diagnosis and initial changes!
