### ISSUE TITLE
Wheel support for linux aarch64

### ISSUE THREAD

**Issue by vrazdalovschi** [fastavro/fastavro#616]
Reopen: https://github.com/fastavro/fastavro/issues/479

The last time `aarch64` was present in the release 1.4.12, but from the 1.15.0 is not present.

Could you return it back?

Thanks!

**Comment by scottbelden** [comment]
Currently the aarch64 builds are done via Travis because it doesn't seem to be supported on Github Actions. Unfortunately, those builds don't always work because of some unknown issues on the Travis platform. The builds will just hang and not complete and if I restart them they will hang at a different point in the build.

All this to say, if you know of a way to build aarch64 wheels more consistently I will try that because Travis isn't very reliable.

Since they aren't reliable currently I try to include them when Travis cooperates but if it is acting up then unfortunately they don't get included.

**Comment by scottbelden** [comment]
I like the second option and I think it is working. Still doing a little tweaking, but hopefully there should be aarch64 wheels in the next release
