### ISSUE TITLE
Infer Avro schema from data in Python

### ISSUE THREAD

**Issue by th0ger** [fastavro/fastavro#635]
Hi fastavro community,

I'm looking for ways to infer (autogenerate) avro schemas from native (json-like) objects in Python.
Any ideas for using `fastavro` for this?

I have not found any libraries for this, besides maybe [spark](https://stackoverflow.com/a/40905477/3806530), which I try to avoid.

**Comment by scottbelden** [comment]
This functionality doesn't exist in fastavro and I don't think it is possible in the general case because of ambiguity.

For example, given a JSON object like this:

```
{
    "field1": "foo",
    "field2": 1,
    "field3": {"subfield1": "bar", "subfield2": "baz"},
}
```

Is `field1` a string type? Or is it an enum type where `foo` is one of the options for the enum?
Is `field2` an int type or a long type?
Is `field3` a record type with those two fields? Or is it a map type whose values are strings?

If in your specific case you have constraints where you know that you will always using `long` instead of `int`, and you will never use maps, and other constraints for ambiguities then it _might_ be possible to do what you want, but it I don't think it's something that would exist in this library since those constraints would differ by end user.

**Comment by th0ger** [comment]
@scottbelden fully agree, I am aware that there will be ambiguity. Sensible defaults, lots of customization and "hinting" would be obvious.
However, Spark does this, so there must be some sensible defaults...

**Comment by scottbelden** [comment]
Yeah, it seems like it could be possible but I don't think this is a feature that will be supported by this library. It sounds like you aren't the only one with this idea, so hopefully you (or someone else) are able to put together a utility for this at some point.
