### ISSUE TITLE
Unable to change the schema of avro file when writing to it in append mode

### ISSUE THREAD

**Issue by evangriffiths** [fastavro/fastavro#657]
I'm looking for a way to modify the schema of an avro file in python. Taking the following example,  using the `fastavro` package, first write out some initial records, with corresponding schema:

```
from fastavro import writer, parse_schema

schema = {
    'name': 'test',
    'type': 'record',
    'fields': [
        {'name': 'id', 'type': 'int'},
        {'name': 'val', 'type': 'long'},
    ],
}
records = [
    {u'id': 1, u'val': 0.2},
    {u'id': 2, u'val': 3.1},
]
with open('test.avro', 'wb') as f:
    writer(f, parse_schema(schema), records)
```

Uhoh, I've got some more records, but they contain `None` values. I'd like to append these records to the avro file, and modify my schema accordingly:
```
more_records = [
    {u'id': 3, u'val': 1.5},
    {u'id': 2, u'val': None},
]
schema['fields'][1]['type'] = ['long', 'null']

with open('test.avro', 'a+b') as f:
    writer(f, parse_schema(schema), more_records)

```

Instead of overwriting the schema, this results in an error:
```
ValueError: Provided schema {'type': 'record', 'name': 'test', 'fields': [{'name': 'id', 'type': 'int'}, {'name': 'val', 'type': ['long', 'null']}], '__fastavro_parsed': True, '__named_schemas': {'test': {'type': 'record', 'name': 'test', 'fields': [{'name': 'id', 'type': 'int'}, {'name': 'val', 'type': ['long', 'null']}]}}} does not match file writer_schema {'type': 'record', 'name': 'test', 'fields': [{'name': 'id', 'type': 'int'}, {'name': 'val', 'type': 'long'}], '__fastavro_parsed': True, '__named_schemas': {'test': {'type': 'record', 'name': 'test', 'fields': [{'name': 'id', 'type': 'int'}, {'name': 'val', 'type': 'long'}]}}}
```

Is there a workaround for this? The [fastavro docs for this](https://fastavro.readthedocs.io/en/latest/writer.html) suggest it's not possible. If not, I'd like to request this as a feature.

**Comment by scottbelden** [comment]
Unfortunately it's not quite that simple. In this example, if you change the original schema to a union, the original data would have to be re-encoded.

For example, assume the original schema is a `string` type and the value is `a`. The binary encoding of that value is `02 61`.

If instead the schema was `["string", "null"]`, that original `a` value would be encoded as `00 02 61` (there is an extra `00` byte because when encoding a union the specification states that there must be an initial byte that represents the position in the union).

So in this specific case if you just simply change the schema in the header, when trying to read the records from the file it would fail.

**Comment by evangriffiths** [comment]
Ah okay. Thanks for the comment. So the workaround is to read the avro file on disk into memory, concat with `more_records`, and write out with the combined schema?

**Comment by scottbelden** [comment]
That's the only thing I can think of at the moment.

**Comment by evangriffiths** [comment]
No worries. Makes sense to close the issue in that case. Thanks.
