### ISSUE TITLE
Optional value in case of logicalType timestamp-mills

### ISSUE THREAD

**Issue by nitishxp** [fastavro/fastavro#667]
Hi, I have the below format for writing a dictionary to Avro file. 
The problem I am facing is that the lastlogin key is not present in all dicts i tried passing the default value but the code is crashing, citing a value must be present.

```
{
    "name": "A",
    "type": "record",
    "fields": [
        {
            "name": "name",
            "type": [
                "null",
                "int"
            ],
            "default": null
        },
        {
            "name": "lastlogin",
            "type": {
                "type": "long",
                "logicalType": "timestamp-millis"
            },
            "default": null
        }
    ]
}
```

**Comment by scottbelden** [comment]
If you could provide the stack trace that would be helpful. However, I'm guessing the problem is that the `lastlogin` field is using a default of `null` without being a union type. So my guess is you need to change `lastlogin` to be a union type (like your `name` field) or provide a default value in the form of a `long`, not `null`.

**Comment by nitishxp** [comment]
I was able to get the result using 
` {
            "name": "lastlogin",
            "type": ["null", 
                  {
                  "type": "long",
                  "logicalType": "timestamp-millis"
              }]
        }`

**Comment by scottbelden** [comment]
Yup, that should do it.
