### ISSUE TITLE
Alias not working when using JSON

### ISSUE THREAD

**Issue by woile** [fastavro/fastavro#669]
Hello, I'm trying to make aliases work with json values but I get an error, I made this reproducible snippet, which shows the normal `write` works as expected, but when using the json it throws an error. I'm not sure if I'm doing something wrong. 
Thanks

```python
from fastavro import writer, reader, json_writer, json_reader
from fastavro.schema import parse_schema
from io import BytesIO, StringIO


# Sample data
input_json = [
    {"nickname": "woile"}
]


old_schema = parse_schema({"type": "record", "name": "Hello", "fields": [{"name": "nickname", "type": "string"}]})

new_schema = parse_schema(
    {"type": "record", "name": "Hello", "fields": [{"name": "name", "type": "string", "aliases": ["nickname"]}]}
)

buffer = BytesIO()
writer(buffer, old_schema, input_json, validator=True)
buffer.seek(0)
for record in reader(buffer, new_schema):
    print(record)
    print("Observe, the alias with an avro binary DOES work")

buffer = StringIO()
json_writer(buffer, old_schema, input_json, validator=True)
buffer.seek(0)

avro_reader = list(json_reader(buffer, new_schema))
for record in avro_reader:
    print(record)
    print("Observe, the alias with a JSON throws an exception")
```

**Comment by scottbelden** [comment]
I'm pretty sure the issue here is that when using the standard binary encoder, a header is included with the original schema and the normal schema evolution processes happen.

However, for the JSON encoder, no header is included containing the original schema. This is similar to how the `schemaless_writer` also includes no header content. [That was resolved in the past](https://github.com/fastavro/fastavro/pull/180) by being able to pass both the original writer schema and the new reader schema so that all the normal schema evolution could work. I imagine we will need to do the same here.

**Comment by woile** [comment]
Interesting, I'm not sure if I'm understanding correctly. But I create a sample for the schemaless_reader without reader_schema, and it still works

```python
from fastavro import schemaless_reader, schemaless_writer
from fastavro.schema import parse_schema
from io import BytesIO, StringIO

input_json = [
    {"nickname": "woile"}
]

old_schema = parse_schema({"type": "record", "name": "Hello", "fields": [{"name": "nickname", "type": "string"}]})

new_schema = parse_schema(
    {"type": "record", "name": "Hello", "fields": [{"name": "name", "type": "string", "aliases": ["nickname"]}]}
)

buffer = BytesIO()
schemaless_writer(buffer, old_schema, input_json[0])
buffer.seek(0)
v = schemaless_reader(buffer, new_schema). # the next parameter is reader_schema, right?
print(v)
print("Observe, the alias with an avro binary DOES work")
```

Am I missing something?
