### ISSUE TITLE
Does fast avro do caching?

### ISSUE THREAD

**Issue by JamesHutchison** [fastavro/fastavro#67]
When sending/receiving many messages with the same schema, does fastavro do any caching to avoid parsing the json definition multiple times?

**Comment by tebeka** [comment]
It current does not cache schema, might be a good idea but we need to profile the cost of caching (mostly computing the hash) vs parsing (the JSON perser is fast)

**Comment by barrywhart** [comment]
If the messages are being read from the same file or stream, the schema is only parsed once. Is that what you're asking, or do you mean each message is a different file or stream?

**Comment by scottbelden** [comment]
I played around with this a little the other day and found that with a relatively simple schema (say something like a record with 4 or 5 fields), I would see that the break even point for when caching will start out performing is around 10 or so calls to `acquaint_schema` with that schema. I would imagine that in most cases users would be processing the same types of records multiple times, so I think it probably does make sense to do some type of caching.

I didn't try with extremely small schemas (e.g. a record with one field). In those cases it might be possible that the time calculating the hash will always be longer than the time it would take just to process the schema.

In general, at some point I'll try to write up a script to automate testing different schemas and report the findings and get a PR in place if the results are still promising.

**Comment by scottbelden** [comment]
I played more with hashing the schema and caching that hash, but I'm not liking the results. In some operations it is faster, but for others it is slower.

Another idea I had was to add an optional argument `parse_schema` to the main functions (`reader`, `writer`, `schemaless_reader`, `schemaless_writer`). It is set to `True` by default (to keep current behavior, but someone could choose to do something like the following:

```python
acquaint_schema(schema)
schemaless_writer(fo, schema, record, parse_schema=False)
```

This would mean the schema is only parsed once rather than every time (which can be quite expensive). I ran t he benchmark script and pasted the output on https://github.com/tebeka/fastavro/pull/214, but for example, currently we get results like so:

```
Writing schemaless 1 records to one file...
... 100000 runs averaged 3.892025947570801e-06 seconds
Reading schemaless 1 records from one file...
... 100000 runs averaged 2.6664161682128905e-06 seconds
```

And by parsing once and setting `parse_schema=False` we get results like this:

```
Writing schemaless 1 records to one file...
... 100000 runs averaged 1.6222906112670899e-06 seconds
Reading schemaless 1 records from one file...
... 100000 runs averaged 1.5092611312866212e-06 seconds
```

Personally I'd like to still be able to find a solution where the knowledge that the schema has been parsed is hidden from the user, but this API of parsing beforehand and signalling so exists within the standard apache/avro library, so it's not that foreign.

**Comment by scottbelden** [comment]
A `parse_schema` function was added in https://github.com/fastavro/fastavro/pull/237 and will return a parsed schema that can be passed in like you would a normal schema. This parsed schema will not be re-parsed and therefore reduces that cost.

For example:
```python
    from fastavro import writer, parse_schema

    schema = {...}
    records = [...]

    parsed_schema = parse_schema(schema)

    with open('weather.avro', 'wb') as out:
        writer(out, parsed_schema, records)
```
